#! /bin/sh

# AUTOSTART
# xdo above -t $(xdo id -n root) $(xdo id -n ~/scripts/lemonlaunch) &
# xdo above -t $(xdo id -n root) $(xdo id -n ~/scripts/lemonconf) &
# xdo above -t $(xdo id -n root) $(xdo id -n lemonbar) &
alsactl -f ~/.asoundconf restore &
dunst &
xrdb ~/.Xresources &
sxhkd &
feh --bg-center /home/sskcvqikf/Pictures/wallpapers/asuka_spears_solarized_bg.png &
setxkbmap -option grp:alt_shift_toggle us,ru,ua &
flameshot &
~/scripts/lemonlaunch &


# MONITORS
bspc monitor -d 1 2 3 4 5 6

bspc config border_width          3
bspc config window_gap            10
bspc config normal_border_color   "#073642"
bspc config focused_border_color  "#839496"
bspc config presel_feedback_color "#073642"

bspc config top_padding           30
bspc config right_padding         30
bspc config bottom_padding        28
bspc config left_padding          30


bspc config split_ratio           0.65
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config automatic_scheme      alternate
