#!/usr/bin/bash

killall lemonbar
killall lemonconf
~/scripts/lemonconf | lemonbar -p -g 1920x15+0+0 -F "#FF839496" -B "#FF002b36" -U "#FF839496" \
-u 2 -o -1 -f 'Source Code Pro'-9 -f 'Font Awesome 5 Free'-10 -f 'Font Awesome 5 Brands'-10 -f 'Font Awesome 5 Free Solid'-10
